# Generated by Django 5.0.8 on 2024-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='direction',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW')], default='HIGH', max_length=5, verbose_name='price direction'),
        ),
    ]
