# Generated by Django 5.1 on 2024-08-11 08:57

import core.utils.enums.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('SUPER ADMINISTRATOR', 'SUPER_ADMINISTRATOR'), ('REGULAR', 'CLIENT')], default='REGULAR', help_text='user account roles and some fdeatures they can handle', max_length=25, verbose_name='user roles'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='whether this user email should be treated as verified.', verbose_name='verified'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('refresh', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('access', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
            },
            bases=(core.utils.enums.base.BaseModelBaseMixin, models.Model),
        ),
    ]
